### ISSUE TITLE
Email regex allows illegal domains

### ISSUE THREAD

**Issue by harpunius** [keeferrourke/pyapa#4]
The current email regex allows for the following emails, none of which are correct.

x@-.dk
x@y-.dk
x@-y.dk
x@y..dk

I hardly see a point in fixing them, as this is not an email-verifying service - what are your thoughts?

**Comment by keeferrourke** [comment]
If you want to fix them, go for it, but the "email" pattern is just used to exclude the match from some of the overlapping error patterns. :smile:

**Comment by keeferrourke** [comment]
I think it's best if this goes unfixed. Even if someone writes an illegal domain in a text file that is being processed by pyapa, I think it's better to have a 'looser' rule here, otherwise more errors may be returned than necessary, possibly with misleading feedback.

**Comment by harpunius** [comment]
I agree
