### ISSUE TITLE
Reference-dot match captures too much

### ISSUE THREAD

**Issue by harpunius** [keeferrourke/pyapa#6]
When run on input

Hans & Yorke (2006) contradict existing literature (Hans and Yorke, 2006).

the program outputs

Match from 9 to 22 for:
Target: Yorke (2006) 
Feedback: References go at the end of sentences; end your sentence after the reference.
Suggestion: Yorke (2006).

which is not correct (from my understanding, and as referenced [here](https://owl.english.purdue.edu/media/jpeg/APAPoster09.jpg).

**Comment by harpunius** [comment]
It seems like this rule is misunderstood. References can occur at any place in a sentence.
See http://www.apastyle.org/manual/related/sample-experiment-paper-1.pdf figure 2.1.

**Comment by keeferrourke** [comment]
Thanks for catching this! One of the biggest problems I had initially writing this package, was the fact that I was (and am) generally unfamiliar with APA style. The refdatedot pattern comes from a [similar program](https://github.com/JonathanAquino/apacheck/blob/master/apacheck.js#L53) and I think I assumed it to be correct.

Glad you caught this, as I don't want to mislead people who are checking their papers.
